sudo: required

services:
        - docker

before_install:
        - docker build -t ledman1001/docker-react -f Dockerfile.dev .

script:
        - docker run ledman1001/docker-react npm run test -- --coverage
        

